name: 'TS Error Check'
description: 'Check the amount of TypeScript and/or ESLint errors on a branch versus main'
inputs:
  repo-token:
    required: true
  cwd:
    description: 'Optional directory to switch to for the build'
  check-typescript:
    description: 'Whether or not to check for TS errors'
    default: true
  check-linting:
    description: 'Whether or not to check for ESLint errors'
    default: true
  ts-script:
    description: 'The script command for the Typescript compiler'
    default: 'npx tsc'
  lint-script:
    description: 'The script command for ESLint'
    default: 'npx eslint'
runs:
  using: 'node12'
  main: 'dist/index.js'
